### ISSUE TITLE
FSM - Circular Buffer

### ISSUE THREAD

**Issue by gmpgreen** [uvic-auvic/Hydrophones#6]
Create usable circular buffer with the data coming off the MAXIM ADC. 

For performance reasons the plan is to use DMA to capture the data from the ADC. Currently I am working the DMA code, so if there are questions about this let me know. Initially we plan to implement FFT on the Jetson using approximately 1000 sample batches (256 for each of the four channels) so whoever is on the UART issue will need to figure out the best way to send these frames of data, and the person writing the FSM will need to set things up accordingly with a data buffer.

(Additional info on ADC behavior on README.md and the MAXIM 1317 datasheet.)

**Comment by poornack** [comment]
Merged to master.
